
User.create(username: "guest", password: "password", picture_url: "https://randomuser.me/api/portraits/women/58.jpg")
User.create(username: "gallardo", password: "password", picture_url: "https://randomuser.me/api/portraits/men/99.jpg")
User.create(username: "eva", password: "password", picture_url: "https://randomuser.me/api/portraits/women/44.jpg")
User.create(username: "neusa", password: "password", picture_url: "https://randomuser.me/api/portraits/women/51.jpg")
User.create(username: "cassandre", password: "password", picture_url: "https://randomuser.me/api/portraits/women/21.jpg")

Restaurant.create(name: "Sagalassos", city: "San Francisco", lat: 37.754699, lng: -122.441700, category_id: 1, owner_id: 1, address: "3650 Market Street", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1472847720/photo-1464786255367-4a86027a5975_v8ksp7.jpg")
Restaurant.create(name: "Helena", city: "San Francisco", lat: 37.800791, lng: -122.405737, category_id: 1, owner_id: 1, address: "3650 Market Street", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1472847720/photo-1464786255367-4a86027a5975_v8ksp7.jpg")
Restaurant.create(name: "Athens", city: "San Francisco", lat: 37.807530, lng: -122.422807, category_id: 1, owner_id: 1, address: "3650 Market Street", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1472847720/photo-1464786255367-4a86027a5975_v8ksp7.jpg")
Restaurant.create(name: "Greek Culture", city: "San Francisco", lat: 37.754699, lng: -122.441700, category_id: 1, owner_id: 1, address: "3650 Market Street", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1472847720/photo-1464786255367-4a86027a5975_v8ksp7.jpg")
Restaurant.create(name: "Sirtaki", city: "Berkeley", lat: 37.873793, lng: -122.289557, category_id: 1, owner_id: 1, address: "3650 Market Street", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1472847720/photo-1464786255367-4a86027a5975_v8ksp7.jpg")
Restaurant.create(name: "Va Chitarra", city: "Berkeley", lat: 37.878960, lng: -122.263374, category_id: 2, owner_id: 1, address: "3650 Market Street", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1472847720/photo-1464786255367-4a86027a5975_v8ksp7.jpg")
Restaurant.create(name: "Pizza Paradise", city: "San Francisco", lat: 37.786916, lng: -122.459809, category_id: 2, owner_id: 1, address: "3650 Market Street", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1472847720/photo-1464786255367-4a86027a5975_v8ksp7.jpg")
Restaurant.create(name: "Venezia", city: "San Francisco", lat: 37.739749, lng: -122.482031, category_id: 2, owner_id: 1, address: "3650 Market Street", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1472847720/photo-1464786255367-4a86027a5975_v8ksp7.jpg")
Restaurant.create(name: "Pizza and Pasta", city: "San Francisco", lat: 37.752771, lng: -122.490329, category_id: 2, owner_id: 1, address: "3650 Market Street", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1472847720/photo-1464786255367-4a86027a5975_v8ksp7.jpg")
Restaurant.create(name: "Sicilian Pizza", city: "Palo Alto", lat: 37.442956, lng: -122.156636, category_id: 2, owner_id: 1, address: "3650 Market Street", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1472847720/photo-1464786255367-4a86027a5975_v8ksp7.jpg")
Restaurant.create(name: "McKing's", city: "San Francisco", lat: 37.772782, lng: -122.417835, category_id: 3, owner_id: 1, address: "81 S Van Ness A", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1472847716/photo-1458677677220-000ddaa037e3_akqzgo.jpg")
Restaurant.create(name: "Burger World", city: "Palo Alto", lat: 37.428247, lng: -122.130509, category_id: 3, owner_id: 1, address: "Matadero Canal", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1472855509/photo-1416772472542-01fdd961f986_atre8i.jpg")
Restaurant.create(name: "Bahnhof", city: "Oakland", lat: 37.808823, lng: -122.294740, category_id: 4, owner_id: 1, address: "1020 Chester Street", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1472847722/photo-1469234496837-d0101f54be3e_srh39o.jpg")
Restaurant.create(name: "Wok", city: "San Francisco", lat: 37.764161, lng: -122.464493, category_id: 5, owner_id: 1, address: "Irving St & 7th Ave", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1472855378/photo-1470256699805-a29e1b58598a_ucyhud.jpg")

reviewer_id = rand(5) + 1
vote = rand(1..5)
restaurant_id = 1
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies fringilla efficitur. Vestibulum purus dolor, finibus efficitur placerat et, consequat at nunc. Proin ullamcorper justo sed eleifend lacinia. Mauris aliquet ex dolor, eu imperdiet felis fermentum vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tempor metus eget neque malesuada tincidunt at et urna. Suspendisse vel ex velit. Etiam nunc sem, porttitor ut magna a, pulvinar commodo nisi. Nunc efficitur arcu nec ipsum faucibus, et blandit libero pellentesque.\nNam porta lacus sed libero rhoncus condimentum. Ut dui orci, pellentesque vitae lectus sed, varius gravida urna. Nullam sed erat augue. Maecenas aliquet sapien erat, non dictum dolor ullamcorper id. Pellentesque pulvinar ullamcorper purus, et feugiat mi elementum nec. Sed pharetra erat sed risus sodales, id iaculis lacus gravida. Sed vulputate auctor elit, id mollis arcu gravida eget. Morbi a ligula sed enim semper condimentum. Donec quis purus orci. Cras sollicitudin enim non ex porta suscipit. Nulla eu sem eget nisl efficitur bibendum. Integer volutpat nibh gravida cursus varius. Pellentesque consequat molestie tristique. Cras varius ultricies nibh vel efficitur."

while restaurant_id <= 14
  rand(3..15).times do
    Review.create(reviewer_id: reviewer_id, restaurant_id: restaurant_id, vote: vote, description: description)
  end
  restaurant_id += 1
end


Review.create(reviewer_id: 1, restaurant_id: 2, vote: 4, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies fringilla efficitur. Vestibulum purus dolor, finibus efficitur placerat et, consequat at nunc. Proin ullamcorper justo sed eleifend lacinia. Mauris aliquet ex dolor, eu imperdiet felis fermentum vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tempor metus eget neque malesuada tincidunt at et urna. Suspendisse vel ex velit. Etiam nunc sem, porttitor ut magna a, pulvinar commodo nisi. Nunc efficitur arcu nec ipsum faucibus, et blandit libero pellentesque.\nNam porta lacus sed libero rhoncus condimentum. Ut dui orci, pellentesque vitae lectus sed, varius gravida urna. Nullam sed erat augue. Maecenas aliquet sapien erat, non dictum dolor ullamcorper id. Pellentesque pulvinar ullamcorper purus, et feugiat mi elementum nec. Sed pharetra erat sed risus sodales, id iaculis lacus gravida. Sed vulputate auctor elit, id mollis arcu gravida eget. Morbi a ligula sed enim semper condimentum. Donec quis purus orci. Cras sollicitudin enim non ex porta suscipit. Nulla eu sem eget nisl efficitur bibendum. Integer volutpat nibh gravida cursus varius. Pellentesque consequat molestie tristique. Cras varius ultricies nibh vel efficitur.")
Review.create(reviewer_id: 1, restaurant_id: 3, vote: 1, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies fringilla efficitur. Vestibulum purus dolor, finibus efficitur placerat et, consequat at nunc. Proin ullamcorper justo sed eleifend lacinia. Mauris aliquet ex dolor, eu imperdiet felis fermentum vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tempor metus eget neque malesuada tincidunt at et urna. Suspendisse vel ex velit. Etiam nunc sem, porttitor ut magna a, pulvinar commodo nisi. Nunc efficitur arcu nec ipsum faucibus, et blandit libero pellentesque.\nNam porta lacus sed libero rhoncus condimentum. Ut dui orci, pellentesque vitae lectus sed, varius gravida urna. Nullam sed erat augue. Maecenas aliquet sapien erat, non dictum dolor ullamcorper id. Pellentesque pulvinar ullamcorper purus, et feugiat mi elementum nec. Sed pharetra erat sed risus sodales, id iaculis lacus gravida. Sed vulputate auctor elit, id mollis arcu gravida eget. Morbi a ligula sed enim semper condimentum. Donec quis purus orci. Cras sollicitudin enim non ex porta suscipit. Nulla eu sem eget nisl efficitur bibendum. Integer volutpat nibh gravida cursus varius. Pellentesque consequat molestie tristique. Cras varius ultricies nibh vel efficitur.")
Review.create(reviewer_id: 2, restaurant_id: 4, vote: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies fringilla efficitur. Vestibulum purus dolor, finibus efficitur placerat et, consequat at nunc. Proin ullamcorper justo sed eleifend lacinia. Mauris aliquet ex dolor, eu imperdiet felis fermentum vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tempor metus eget neque malesuada tincidunt at et urna. Suspendisse vel ex velit. Etiam nunc sem, porttitor ut magna a, pulvinar commodo nisi. Nunc efficitur arcu nec ipsum faucibus, et blandit libero pellentesque.\nNam porta lacus sed libero rhoncus condimentum. Ut dui orci, pellentesque vitae lectus sed, varius gravida urna. Nullam sed erat augue. Maecenas aliquet sapien erat, non dictum dolor ullamcorper id. Pellentesque pulvinar ullamcorper purus, et feugiat mi elementum nec. Sed pharetra erat sed risus sodales, id iaculis lacus gravida. Sed vulputate auctor elit, id mollis arcu gravida eget. Morbi a ligula sed enim semper condimentum. Donec quis purus orci. Cras sollicitudin enim non ex porta suscipit. Nulla eu sem eget nisl efficitur bibendum. Integer volutpat nibh gravida cursus varius. Pellentesque consequat molestie tristique. Cras varius ultricies nibh vel efficitur.")
Review.create(reviewer_id: 2, restaurant_id: 5, vote: 5, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies fringilla efficitur. Vestibulum purus dolor, finibus efficitur placerat et, consequat at nunc. Proin ullamcorper justo sed eleifend lacinia. Mauris aliquet ex dolor, eu imperdiet felis fermentum vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tempor metus eget neque malesuada tincidunt at et urna. Suspendisse vel ex velit. Etiam nunc sem, porttitor ut magna a, pulvinar commodo nisi. Nunc efficitur arcu nec ipsum faucibus, et blandit libero pellentesque.\nNam porta lacus sed libero rhoncus condimentum. Ut dui orci, pellentesque vitae lectus sed, varius gravida urna. Nullam sed erat augue. Maecenas aliquet sapien erat, non dictum dolor ullamcorper id. Pellentesque pulvinar ullamcorper purus, et feugiat mi elementum nec. Sed pharetra erat sed risus sodales, id iaculis lacus gravida. Sed vulputate auctor elit, id mollis arcu gravida eget. Morbi a ligula sed enim semper condimentum. Donec quis purus orci. Cras sollicitudin enim non ex porta suscipit. Nulla eu sem eget nisl efficitur bibendum. Integer volutpat nibh gravida cursus varius. Pellentesque consequat molestie tristique. Cras varius ultricies nibh vel efficitur.")
Review.create(reviewer_id: 2, restaurant_id: 1, vote: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies fringilla efficitur. Vestibulum purus dolor, finibus efficitur placerat et, consequat at nunc. Proin ullamcorper justo sed eleifend lacinia. Mauris aliquet ex dolor, eu imperdiet felis fermentum vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tempor metus eget neque malesuada tincidunt at et urna. Suspendisse vel ex velit. Etiam nunc sem, porttitor ut magna a, pulvinar commodo nisi. Nunc efficitur arcu nec ipsum faucibus, et blandit libero pellentesque.\nNam porta lacus sed libero rhoncus condimentum. Ut dui orci, pellentesque vitae lectus sed, varius gravida urna. Nullam sed erat augue. Maecenas aliquet sapien erat, non dictum dolor ullamcorper id. Pellentesque pulvinar ullamcorper purus, et feugiat mi elementum nec. Sed pharetra erat sed risus sodales, id iaculis lacus gravida. Sed vulputate auctor elit, id mollis arcu gravida eget. Morbi a ligula sed enim semper condimentum. Donec quis purus orci. Cras sollicitudin enim non ex porta suscipit. Nulla eu sem eget nisl efficitur bibendum. Integer volutpat nibh gravida cursus varius. Pellentesque consequat molestie tristique. Cras varius ultricies nibh vel efficitur.")
Review.create(reviewer_id: 3, restaurant_id: 2, vote: 3, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies fringilla efficitur. Vestibulum purus dolor, finibus efficitur placerat et, consequat at nunc. Proin ullamcorper justo sed eleifend lacinia. Mauris aliquet ex dolor, eu imperdiet felis fermentum vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tempor metus eget neque malesuada tincidunt at et urna. Suspendisse vel ex velit. Etiam nunc sem, porttitor ut magna a, pulvinar commodo nisi. Nunc efficitur arcu nec ipsum faucibus, et blandit libero pellentesque.\nNam porta lacus sed libero rhoncus condimentum. Ut dui orci, pellentesque vitae lectus sed, varius gravida urna. Nullam sed erat augue. Maecenas aliquet sapien erat, non dictum dolor ullamcorper id. Pellentesque pulvinar ullamcorper purus, et feugiat mi elementum nec. Sed pharetra erat sed risus sodales, id iaculis lacus gravida. Sed vulputate auctor elit, id mollis arcu gravida eget. Morbi a ligula sed enim semper condimentum. Donec quis purus orci. Cras sollicitudin enim non ex porta suscipit. Nulla eu sem eget nisl efficitur bibendum. Integer volutpat nibh gravida cursus varius. Pellentesque consequat molestie tristique. Cras varius ultricies nibh vel efficitur.")
Review.create(reviewer_id: 4, restaurant_id: 3, vote: 1, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies fringilla efficitur. Vestibulum purus dolor, finibus efficitur placerat et, consequat at nunc. Proin ullamcorper justo sed eleifend lacinia. Mauris aliquet ex dolor, eu imperdiet felis fermentum vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tempor metus eget neque malesuada tincidunt at et urna. Suspendisse vel ex velit. Etiam nunc sem, porttitor ut magna a, pulvinar commodo nisi. Nunc efficitur arcu nec ipsum faucibus, et blandit libero pellentesque.\nNam porta lacus sed libero rhoncus condimentum. Ut dui orci, pellentesque vitae lectus sed, varius gravida urna. Nullam sed erat augue. Maecenas aliquet sapien erat, non dictum dolor ullamcorper id. Pellentesque pulvinar ullamcorper purus, et feugiat mi elementum nec. Sed pharetra erat sed risus sodales, id iaculis lacus gravida. Sed vulputate auctor elit, id mollis arcu gravida eget. Morbi a ligula sed enim semper condimentum. Donec quis purus orci. Cras sollicitudin enim non ex porta suscipit. Nulla eu sem eget nisl efficitur bibendum. Integer volutpat nibh gravida cursus varius. Pellentesque consequat molestie tristique. Cras varius ultricies nibh vel efficitur.")
Review.create(reviewer_id: 4, restaurant_id: 4, vote: 4, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies fringilla efficitur. Vestibulum purus dolor, finibus efficitur placerat et, consequat at nunc. Proin ullamcorper justo sed eleifend lacinia. Mauris aliquet ex dolor, eu imperdiet felis fermentum vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tempor metus eget neque malesuada tincidunt at et urna. Suspendisse vel ex velit. Etiam nunc sem, porttitor ut magna a, pulvinar commodo nisi. Nunc efficitur arcu nec ipsum faucibus, et blandit libero pellentesque.\nNam porta lacus sed libero rhoncus condimentum. Ut dui orci, pellentesque vitae lectus sed, varius gravida urna. Nullam sed erat augue. Maecenas aliquet sapien erat, non dictum dolor ullamcorper id. Pellentesque pulvinar ullamcorper purus, et feugiat mi elementum nec. Sed pharetra erat sed risus sodales, id iaculis lacus gravida. Sed vulputate auctor elit, id mollis arcu gravida eget. Morbi a ligula sed enim semper condimentum. Donec quis purus orci. Cras sollicitudin enim non ex porta suscipit. Nulla eu sem eget nisl efficitur bibendum. Integer volutpat nibh gravida cursus varius. Pellentesque consequat molestie tristique. Cras varius ultricies nibh vel efficitur.")
Review.create(reviewer_id: 5, restaurant_id: 5, vote: 5, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies fringilla efficitur. Vestibulum purus dolor, finibus efficitur placerat et, consequat at nunc. Proin ullamcorper justo sed eleifend lacinia. Mauris aliquet ex dolor, eu imperdiet felis fermentum vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tempor metus eget neque malesuada tincidunt at et urna. Suspendisse vel ex velit. Etiam nunc sem, porttitor ut magna a, pulvinar commodo nisi. Nunc efficitur arcu nec ipsum faucibus, et blandit libero pellentesque.\nNam porta lacus sed libero rhoncus condimentum. Ut dui orci, pellentesque vitae lectus sed, varius gravida urna. Nullam sed erat augue. Maecenas aliquet sapien erat, non dictum dolor ullamcorper id. Pellentesque pulvinar ullamcorper purus, et feugiat mi elementum nec. Sed pharetra erat sed risus sodales, id iaculis lacus gravida. Sed vulputate auctor elit, id mollis arcu gravida eget. Morbi a ligula sed enim semper condimentum. Donec quis purus orci. Cras sollicitudin enim non ex porta suscipit. Nulla eu sem eget nisl efficitur bibendum. Integer volutpat nibh gravida cursus varius. Pellentesque consequat molestie tristique. Cras varius ultricies nibh vel efficitur.")
Review.create(reviewer_id: 5, restaurant_id: 1, vote: 3, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies fringilla efficitur. Vestibulum purus dolor, finibus efficitur placerat et, consequat at nunc. Proin ullamcorper justo sed eleifend lacinia. Mauris aliquet ex dolor, eu imperdiet felis fermentum vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tempor metus eget neque malesuada tincidunt at et urna. Suspendisse vel ex velit. Etiam nunc sem, porttitor ut magna a, pulvinar commodo nisi. Nunc efficitur arcu nec ipsum faucibus, et blandit libero pellentesque.\nNam porta lacus sed libero rhoncus condimentum. Ut dui orci, pellentesque vitae lectus sed, varius gravida urna. Nullam sed erat augue. Maecenas aliquet sapien erat, non dictum dolor ullamcorper id. Pellentesque pulvinar ullamcorper purus, et feugiat mi elementum nec. Sed pharetra erat sed risus sodales, id iaculis lacus gravida. Sed vulputate auctor elit, id mollis arcu gravida eget. Morbi a ligula sed enim semper condimentum. Donec quis purus orci. Cras sollicitudin enim non ex porta suscipit. Nulla eu sem eget nisl efficitur bibendum. Integer volutpat nibh gravida cursus varius. Pellentesque consequat molestie tristique. Cras varius ultricies nibh vel efficitur.")

Category.create(title: "Greek", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1473229330/noun_437044_cc_m4cyud.png")
Category.create(title: "Italian", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1473230741/noun_158755_cc_unirdj.png")
Category.create(title: "American", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1473229519/noun_304697_cc_p1kvbu.png")
Category.create(title: "German", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1473229895/noun_171213_cc_qe26kj.png")
Category.create(title: "Asian", image_url: "https://res.cloudinary.com/dguiepgvw/image/upload/v1473230000/noun_8078_cc_yt7xx6.png")
